/**
 * SH1106 OLED Display Example for Keil C (STM32)
 * 
 * This example shows how to use the SH1106 library to display "Hello World"
 * on an SH1106 OLED display connected via I2C.
 * 
 * Hardware Requirements:
 * - STM32F10x microcontroller
 * - SH1106 OLED Display (128x64)
 * - I2C connection: SDA to PB7, SCL to PB6
 * 
 * Software Requirements:
 * - STM32CubeMX generated code with I2C1 enabled
 * - fonts.c and fonts.h files
 * - sh1106.c and sh1106.h files
 */

#include "main.h"
#include "sh1106.h"

/* Example usage in main.c */
int main(void)
{
    /* HAL initialization (generated by STM32CubeMX) */
    HAL_Init();
    
    /* Configure the system clock (generated by STM32CubeMX) */
    SystemClock_Config();
    
    /* Initialize all configured peripherals (generated by STM32CubeMX) */
    MX_GPIO_Init();
    MX_I2C1_Init();  // This should be generated by STM32CubeMX
    
    /* Initialize SH1106 display */
    if (SH1106_Init()) {
        /* Display initialization successful */
        
        /* Display Hello World */
        SH1106_HelloWorld();
        
        /* Wait for a moment */
        HAL_Delay(2000);
        
        /* Alternative method - manual text display */
        SH1106_Clear();
        SH1106_GotoXY(0, 0);
        SH1106_Puts("Manual Text", &Font_11x18, SH1106_COLOR_WHITE);
        SH1106_GotoXY(0, 25);
        SH1106_Puts("Line 2", &Font_7x10, SH1106_COLOR_WHITE);
        SH1106_UpdateScreen();
        
    } else {
        /* Display initialization failed */
        /* Handle error here - maybe blink an LED */
        while(1) {
            HAL_Delay(500);
            // Blink error LED or handle error
        }
    }

    /* Infinite loop */
    while (1)
    {
        /* Your main application code here */
        
        /* Example: Update display every second */
        HAL_Delay(1000);
        
        /* You can add more display updates here */
    }
}

/**
 * Example function to display different text
 */
void DisplayCustomText(char* line1, char* line2, char* line3) {
    SH1106_Clear();
    
    SH1106_GotoXY(5, 5);
    SH1106_Puts(line1, &Font_11x18, SH1106_COLOR_WHITE);
    
    SH1106_GotoXY(5, 25);
    SH1106_Puts(line2, &Font_7x10, SH1106_COLOR_WHITE);
    
    SH1106_GotoXY(5, 40);
    SH1106_Puts(line3, &Font_7x10, SH1106_COLOR_WHITE);
    
    SH1106_UpdateScreen();
}

/**
 * Example function to display sensor data
 */
void DisplaySensorData(float temperature, float humidity) {
    char temp_str[20];
    char hum_str[20];
    
    sprintf(temp_str, "Temp: %.1fC", temperature);
    sprintf(hum_str, "Hum: %.1f%%", humidity);
    
    SH1106_Clear();
    
    SH1106_GotoXY(10, 10);
    SH1106_Puts("Sensor Data", &Font_11x18, SH1106_COLOR_WHITE);
    
    SH1106_GotoXY(5, 35);
    SH1106_Puts(temp_str, &Font_7x10, SH1106_COLOR_WHITE);
    
    SH1106_GotoXY(5, 50);
    SH1106_Puts(hum_str, &Font_7x10, SH1106_COLOR_WHITE);
    
    SH1106_UpdateScreen();
}

/**
 * Example function to draw simple graphics
 */
void DisplayGraphics(void) {
    SH1106_Clear();
    
    /* Draw rectangle */
    SH1106_DrawRectangle(10, 10, 50, 30, SH1106_COLOR_WHITE);
    
    /* Draw filled rectangle */
    SH1106_DrawFilledRectangle(70, 10, 30, 20, SH1106_COLOR_WHITE);
    
    /* Draw lines */
    SH1106_DrawLine(0, 50, 127, 50, SH1106_COLOR_WHITE);
    SH1106_DrawLine(64, 0, 64, 63, SH1106_COLOR_WHITE);
    
    SH1106_UpdateScreen();
}

/* 
 * NOTE: Make sure to include the following files in your Keil project:
 * 1. sh1106.c
 * 2. sh1106.h  
 * 3. fonts.c (from the GitHub repository)
 * 4. fonts.h (from the GitHub repository)
 * 
 * Also ensure that I2C1 is properly configured in STM32CubeMX:
 * - I2C1 should be enabled
 * - SDA pin: PB7
 * - SCL pin: PB6  
 * - Standard mode (100 kHz) or Fast mode (400 kHz)
 */